//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipal_v2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenefitService
    {
        public int benefit_service_id { get; set; }
        public int benefit_id { get; set; }
        public int service_id { get; set; }
    
        public virtual Benefit Benefit { get; set; }
        public virtual Service Service { get; set; }
    }
}
