//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipal_v2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Counter()
        {
            this.Public_utilities = new HashSet<Public_utilities>();
        }
    
        public int counter_id { get; set; }
        public Nullable<int> apartment_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public double indications { get; set; }
        public Nullable<bool> bit { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual HouseService HouseService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Public_utilities> Public_utilities { get; set; }
    }
}
