//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipal_v2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class House_public_utilities
    {
        public int house_public_utilities_id { get; set; }
        public Nullable<int> house_service_id { get; set; }
        public float used { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> house_counter_id { get; set; }
    
        public virtual House_counter House_counter { get; set; }
        public virtual HouseService HouseService { get; set; }
    }
}
