//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipal_v2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individual_amount
    {
        public int individual_amount_id { get; set; }
        public Nullable<int> house_service_id { get; set; }
        public Nullable<double> used { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> house_id { get; set; }
    
        public virtual House House { get; set; }
        public virtual HouseService HouseService { get; set; }
    }
}
