//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipal_v2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_UK
    {
        public int id { get; set; }
        public string uk_name { get; set; }
        public string INN { get; set; }
        public string r_s { get; set; }
        public string name_bank { get; set; }
        public string k_s { get; set; }
        public string BIK { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
    }
}
