//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipal_v2._0.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class municipalDBEntities : DbContext
    {
        public municipalDBEntities()
            : base("name=municipalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<Benefit> Benefit { get; set; }
        public virtual DbSet<BenefitService> BenefitService { get; set; }
        public virtual DbSet<Counter> Counter { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<House_counter> House_counter { get; set; }
        public virtual DbSet<House_public_utilities> House_public_utilities { get; set; }
        public virtual DbSet<HouseService> HouseService { get; set; }
        public virtual DbSet<Individual_amount> Individual_amount { get; set; }
        public virtual DbSet<info_UK> info_UK { get; set; }
        public virtual DbSet<Maintenance_and_repair> Maintenance_and_repair { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<OwnerBenefit> OwnerBenefit { get; set; }
        public virtual DbSet<Personal_account> Personal_account { get; set; }
        public virtual DbSet<Public_utilities> Public_utilities { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_payment> Type_payment { get; set; }
        public virtual DbSet<Type_service> Type_service { get; set; }
    }
}
