//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipal_v2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerBenefit
    {
        public int owner_benefit_id { get; set; }
        public int owner_id { get; set; }
        public Nullable<int> benefit_id { get; set; }
    
        public virtual Benefit Benefit { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
