//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipal_v2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Owner()
        {
            this.OwnerBenefit = new HashSet<OwnerBenefit>();
            this.Personal_account = new HashSet<Personal_account>();
        }
    
        public int owner_id { get; set; }
        public string surname { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public int gender_id { get; set; }
        public System.DateTime birthday { get; set; }
        public string phone_number { get; set; }
        public int series_passport { get; set; }
        public string number_passport { get; set; }
        public System.DateTime date_passport { get; set; }
        public string who_issued_passport { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnerBenefit> OwnerBenefit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personal_account> Personal_account { get; set; }
    }
}
